# Generated by Django 5.0.6 on 2025-04-09 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_profile_email_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email_token',
            field=models.CharField(default='d17fd611-d30d-4146-adc3-d27f6ba5e521', max_length=100, unique=True),
        ),
    ]
